//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokémonGoManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokémonGoManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psydu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NamesEN {
            get {
                return ResourceManager.GetString("NamesEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulbizarre
        ///Herbizarre
        ///Florizarre
        ///Salamèche
        ///Reptincel
        ///Dracaufeu
        ///Carapuce
        ///Carabaffe
        ///Tortank
        ///Chenipan
        ///Chrysacier
        ///Papilusion
        ///Aspicot
        ///Coconfort
        ///Dardargnan
        ///Roucool
        ///Roucoups
        ///Roucarnage
        ///Rattata
        ///Rattatac
        ///Piafabec
        ///Rapasdepic
        ///Abo
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sabelette
        ///Sablaireau
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Mélofée
        ///Mélodelfe
        ///Goupix
        ///Feunard
        ///Rondoudou
        ///Grodoudou
        ///Nosferapti
        ///Nosferalto
        ///Mystherbe
        ///Ortide
        ///Rafflesia
        ///Paras
        ///Parasect
        ///Mimitoss
        ///Aéromite
        ///Taupiqueur
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NamesFR {
            get {
                return ResourceManager.GetString("NamesFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pokemon {
            get {
                object obj = ResourceManager.GetObject("Pokemon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall, your Pokémon has room for improvement as far as battling goes.
        ///Overall, your Pokémon is pretty decent!
        ///Overall, your Pokémon is really strong!
        ///Overall, your Pokémon looks like it can really battle with the best of them!
        ///Its stats are all right, but kinda basic, as far as I can see.
        ///It&apos;s definitely got some good stats. Definitely!
        ///Its stats are really strong! Impressive.
        ///Its stats are the best I&apos;ve ever seen! No doubt about it!
        ///Dans l&apos;ensemble, ton Pokémon peut devenir un meilleur combattant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextInstinct {
            get {
                return ResourceManager.GetString("TextInstinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall, your Pokémon is not likely to make much headway in battle.
        ///Overall, your Pokémon is above average
        ///Overall, your Pokémon has caught my attention
        ///Overall, your Pokémon is a wonder! What a breathtaking Pokémon!
        ///Its stats are not out of the norm, in my estimation.
        ///Its stats are noticeably trending to the positive.
        ///I&apos;m certainly impressed by its stats, I must say.
        ///Its stats exceed my calculations. It&apos;s incredible!
        ///Dans l&apos;ensemble, ton Pokémon n&apos;ira pas très loin au combat.
        ///Dans l&apos;ensemble, ton  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextMystic {
            get {
                return ResourceManager.GetString("TextMystic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextValor {
            get {
                return ResourceManager.GetString("TextValor", resourceCulture);
            }
        }
    }
}
